### ISSUE TITLE
D2RMM 1.5.0 - needs an update

### ISSUE THREAD

**Issue by mattish91** [Schwartzalexander/D2RPowerfulUniques#1]
Durring install im reciving: an error which i can't explain as im not a mod developer my self.

In the D2RMM log im getting this:

'Mod Powerful uniques encountered an error! ReferenceError: skillTreeIndex is not defined at addGeneralUniques (mod.js:415:29) at mod.js:51:1 at mod.js:574:3 at VM.runScript (C:\Users\matti\OneDrive - Mspot.se\Desktop\D2RMM\D2RMM-169-1-5-0-1697940812\D2RMM 1.5.0\resources\app.asar\node_modules\vm2\lib\mod.js:287:18) at C:\Users\matti\OneDrive - Mspot.se\Desktop\D2RMM\D2RMM-169-1-5-0-1697940812\D2RMM 1.5.0\resources\app.asar\node_modules\vm2\lib\mod.js:511:16 at doWithTimeout (C:\Users
12:32:16 PM'

Maybe you could release an update when you got time? 😀

**Comment by mattish91** [comment]
Seams to be working fine when "Use legacy Snake-oil flavoured rock" setting is enabled. not sure what exactly that does tho.
